languageCode = "en-us"
title = "Brain Baking"
baseurl = "http://www.brainbaking.com/"
enableEmoji = true
theme = "beautifulbaking"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "brainbaking"
googleAnalytics = "UA-45748221-1"

publishDir = "docs"

[taxonomies]
tag = "tags"

[Params]
  subtitle = "Freshly baked thoughts"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  name = "Wouter Groeneveld"
  email = "wouter.groeneveld@gmail.com"
  #facebook = "username"
  github = "wgroeneveld"
  #twitter = "woutergroenev"
  #linkedin = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #soundcloud = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #spotify = "username"
  #itchio = "username"
  pinterest = "woutergroenev"
  goodreads = "5451893-wouter"

[[menu.main]]
    name = "Menu"
    url = "/"
    weight = 1
    pre = "<i class='fa fa-home'></i>"

[[menu.main]]
    name = "Wiki"
    parent = "Menu"
    url = "/wiki/"
    pre = "<i class='fa fa-wikipedia-w'></i>"
    weight = 1

[[menu.main]]
    name = "Tags"
    parent = "Menu"
    url = "/tags"
    pre = "<i class='fa fa-tags'></i>"
    weight = 2

[[menu.main]]
    name = "About me"
    parent = "Menu"
    url = "/about"
    pre = "<i class='fa fa-address-card-o'></i>"
    weight = 3

[[menu.main]]
    name = "Talks"
    pre = "<i class='fa fa-graduation-cap'></i>"
    parent = "Menu"
    url = "/talks"
    weight = 4
